trigger: none

pool:
  vmImage: 'windows-latest'
variables:
- group: FitnessApp-Variables
- name: buildConfiguration
  value: 'Release'
- name: publishDir
  value: '$(Build.ArtifactStagingDirectory)/publish'
- name: projectPath
  value: '**/*.csproj'
- name: nupkgDir
  value: '$(Build.ArtifactStagingDirectory)/nupkg'

steps:
# Step 1: Install .NET SDK
- task: UseDotNet@2
  displayName: 'Install .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'
    includePreviewVersions: true

# Step 2: Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(projectPath)'

# Step 3: Build project
- task: DotNetCoreCLI@2
  displayName: 'Build project'
  inputs:
    command: 'build'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

# Step 4: Publish project to folder
- task: DotNetCoreCLI@2
  displayName: 'Publish project'
  inputs:
    command: 'publish'
    projects: '$(projectPath)'
    arguments: '--configuration $(buildConfiguration) --output $(publishDir) --no-restore'

# Step 5: Pack project into NuGet package
- task: DotNetCoreCLI@2
  displayName: 'Pack project into NuGet package'
  inputs:
    command: 'pack'
    packagesToPack: '$(projectPath)'
    configuration: 'Release'
    outputDir: '$(nupkgDir)'

# Step 6: Push NuGet package to Azure Artifacts Feed
- task: NuGetCommand@2
  displayName: 'Push NuGet package to Azure Artifacts Feed'
  inputs:
    command: 'push'
    packagesToPush: '$(nupkgDir)/*.nupkg'
    publishVstsFeed: 'FitnessAppPackages'

# Step 7: Publish build artifacts (optional)
- task: PublishBuildArtifacts@1
  displayName: 'Publish build artifacts'
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Step 8: Restore package from Azure Artifacts feed
- task: NuGetCommand@2
  displayName: 'Restore FitnessApp package from feed'
  inputs:
    command: restore
    restoreSolution: '**/*.sln'
    feedsToUse: select
    vstsFeed: 'FitnessAppPackages'

# Step 9: Download previously published DLLs artifact (optional)
- task: DownloadPipelineArtifact@2
  displayName: 'Download DLLs artifact'
  inputs:
    artifact: 'FitnessAppDLLs'
    path: '$(Build.SourcesDirectory)/fitnessapp_dlls'

# Step 10: Deploy to Azure App Service
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(appServiceName)'
    package: '$(Build.SourcesDirectory)/fitnessapp_dlls/*'
    deploymentMethod: 'auto'
    takeAppOfflineFlag: true
    enableCustomDeployment: true



