trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
- group: FitnessApp-Variables   # Library se variables le raha hai
- name: buildConfiguration
  value: 'Release'
- name: publishDir
  value: '$(Build.ArtifactStagingDirectory)/publish'

steps:
# Step 1: Install .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

# Step 2: Restore
- script: dotnet restore
  displayName: 'Restore packages'

# Step 3: Build
- script: dotnet build --configuration $(buildConfiguration) --no-restore
  displayName: 'Build project'

# Step 4: Publish
- script: dotnet publish --configuration $(buildConfiguration) --no-restore --output $(publishDir)
  displayName: 'Publish project'

# Step 5: Publish artifacts (optional)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(publishDir)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Step 6: Deploy to App Service (variables from Library)
- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureServiceConnection)'
    appName: '$(appServiceName)'
    package: '$(publishDir)'

